# Generated by Django 5.2.3 on 2025-06-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('technologies', models.CharField()),
            ],
        ),
    ]
