# Generated by Django 5.2.3 on 2025-06-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
