# Generated by Django 5.2.3 on 2025-07-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_location_job_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location_name',
        ),
    ]
