# Generated by Django 5.2.3 on 2025-07-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_job_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='text',
            field=models.CharField(null=True),
        ),
    ]
