# Generated by Django 5.2.3 on 2025-07-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_remove_job_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location',
        ),
    ]
