# Generated by Django 5.2.3 on 2025-07-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_rename_name_location_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='name',
            new_name='title',
        ),
    ]
