# Generated by Django 5.2.3 on 2025-07-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_rename_name_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('Ashgabat', 'Ashgabat'), ('Mary', 'Mary'), ('Dashoguz', 'Dashoguz')], default='Ashgabat', max_length=256),
        ),
    ]
