# Generated by Django 5.2.3 on 2025-07-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
