# Generated by Django 5.2.3 on 2025-07-03 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_location_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='title',
            new_name='name',
        ),
    ]
