# Generated by Django 5.2.3 on 2025-07-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_rename_title_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(choices=[('ashgabat', 'Ashgabat'), ('mary', 'Mary'), ('dashoguz', 'Dashoguz')], default='Ashgabat', max_length=256),
        ),
    ]
