# Generated by Django 5.2.3 on 2025-07-04 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_remove_job_location_remove_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='job.job'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, choices=[('ashgabat', 'Ashgabat'), ('mary', 'Mary'), ('dashoguz', 'Dashoguz')], default='Ashgabat', max_length=256, null=True),
        ),
    ]
