# Generated by Django 5.2.3 on 2025-07-04 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_location_job_alter_location_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job.job'),
        ),
    ]
